steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/firebase/builder', '.']
images:
- 'europe-docker.pkg.dev/$PROJECT_ID/firebase/builder'
tags: ['firebase']